### ISSUE TITLE
Adding/Altering space within and between components?

### ISSUE THREAD

**Issue by stemarf50** [redgeoff/mson-react#100]
As the title suggests, I would like to know how I can change the space between components. For instance, in my form, I would like to have more space above my "headings" and less space below them. May I please know how I can achieve that here?

**Comment by joshglenn** [comment]
You can do that by modifying and/or overriding css attributes to get the look you want.

Or, you could modify the code in mson-react if you know javascript and react well enough.

**Comment by redgeoff** [comment]
mson-react uses [Material-UI](https://material-ui-next.com/). I think you may be able to play with the [themes](https://material-ui.com/customization/themes/#themes) to accomplish this. If not, as per @joshglenn's suggestion, you can modify the CSS or Material-UI components.
