### ISSUE TITLE
Is it possible to render only the form without the menu and left navbar?

### ISSUE THREAD

**Issue by mukundanma** [redgeoff/mson-react#106]
I am using React + Material UI to build a web application. There are a few forms that are required as part of the application.
I have been able to render the form generated using mson-react but it displays the menu and the side nav.
Is it possible to render only the form without the menu and left navbar?

**Comment by joshglenn** [comment]
You mean, so it looks like this:

<img width="502" alt="Screen Shot 2019-04-25 at 3 50 18 PM" src="https://user-images.githubusercontent.com/6953274/56767756-2e2acb80-6772-11e9-9700-f14f49c08709.png">

Yes, it's possible, but I don't think it is "built-in" functionality in mson-react. I'm not sure what would be the best way to do that (Geoff would know better than I). But here are some options to consider:

## Option 1: 

To make the menu and the header disappear after rendering, leaving only the form, you can do the following by manipulating the DOM. (Problem is, you'd need a way of knowing if everything re-rendered. Then, you would need to do it all over again):

- remove the material UI drawer component from the DOM
- remove all classes from the header element as well as removing the toolbar div from inside the header element
- then, override a couple of CSS rules, specifically the #main margin-top and the media query rule that changes the left margin of the main element when the screen width exceeds 960 pixels 

## Option 2

But it may be better to never render the items in the first place. If that's the direction you want to go, you could modify '/src/app.js' by modifying a few lines of lines of code. I have tried this method, and it works! But, this will make your copy of mson-react different from the master branch here on Github.

First, remove or comment lines [594 and 595](https://github.com/redgeoff/mson-react/blob/190b109a507f51eadd0ef37edaaffac3e724c526/src/app.js#L594-L595). 

<img width="1231" alt="Screen Shot 2019-04-25 at 4 09 18 PM" src="https://user-images.githubusercontent.com/6953274/56768684-a6928c00-6774-11e9-8303-6dab51dc0fc1.png">

This will stop the app from rendering the menu drawer or the header. But, the space where they were will still be there. So, make the modifications to lines 598, 599 as shown above.

Also, make the following change to remove some other css so the header margin is removed, leaving only the form... [go here to see the code you would be changing](https://github.com/redgeoff/mson-react/blob/190b109a507f51eadd0ef37edaaffac3e724c526/src/app.js#L66-L70)

<img width="1230" alt="Screen Shot 2019-04-25 at 4 08 54 PM" src="https://user-images.githubusercontent.com/6953274/56768891-31738680-6775-11e9-80b3-bb4b8409526a.png">

Be careful, there are lots of app.js files in mson-react (in different folders). Make sure you are editing the right one :-).

## Option 3

Using a new feature in react called portals, you may be able to write a "plugin" that does what you need. I haven't tried this I don't know what the potential pitfalls might be. For your reference, you may want to [read this article](https://www.deadcoderising.com/react-16-render-a-child-component-into-another-dom-node-using-portals/).

I hope this helps!

P.S. Here is a [github gist of the modified app.js file](https://gist.github.com/joshglenn/0616a762b1ec0df1fd27bce4d7812d2f) (from option 2 above) for your reference:

**Comment by redgeoff** [comment]
@joshglenn those are some nice workarounds!

You can actually do this in MSON already using `fullscreen: true`, e.g. check out this new [MSON: No Menu](https://codesandbox.io/s/w00kmwwn2l?fontsize=14) demo.

Sorry that the docs are sparse, been busy ;)

**Comment by mukundanma** [comment]
Thanks for your responses. I will try the above and let you know if I have any more questions.
