### ISSUE TITLE
Querystring in mson / mson-react

### ISSUE THREAD

**Issue by joshglenn** [redgeoff/mson-react#120]
I see in app.js that the queryString gets saved into a globals object:

https://github.com/redgeoff/mson-react/blob/1ecd7fb40d4541d722153073dbf01fc6a66bc5b5/src/app.js#L247-L253

My question is, at the component level, or in MSON, how do I access that queryString to use its data in a specific component? 

For example, I have tried:

```
import globals from 'mson/lib/globals';
```

then 

```
console.log(globals);
console.log(globals.get('route'));
```

and although those functions work and output object info to the console, the global route object that got set in app.js does not appear to be available in other components. It is just empty.

Shouldn't those globals be accessible to me? Any idea what I might be doing wrong?

**Comment by joshglenn** [comment]
For example, let's say I wanted to extend the `Edit Contact` page of the MSON Demo to edit and/or create a contact with the id of 99. I would type in a url like this

```
http://localhost:3000/mson-react/contact/edit?id=99
```

How would I modify the demo app so that it would know dynamically based on the querystring which contact to edit?

**Comment by redgeoff** [comment]
Great question @joshglenn. There is a convention that works for route parameters, but I need to find some time to create an example. The gist is that you can do things like:
```
      {
        path: '/contact/edit/:id',
        content: ...
      },
```
and then create a field in the component named `id` that will get the value

**Comment by joshglenn** [comment]
Thanks for the tip. That was all I needed to get pointed in the right direction. This is now [documented in the docs](https://mson-docs.readthedocs.io/en/latest/mson-react.html). Let me know if I missed any key details.
