### ISSUE TITLE
i can't run proyect

### ISSUE THREAD

**Issue by MedinaGitHub** [redgeoff/mson-react#191]
when i run project and i going to press some route in menu, appear this error

![image](https://user-images.githubusercontent.com/16387514/84703348-1be79000-af26-11ea-8b5a-b5a9b97ceaf0.png)

i started the project as follows

npm install
npm start
click some route
Crash =/
@redgeoff

**Comment by redgeoff** [comment]
Please see the directions at https://github.com/redgeoff/mson#mson-demo
