### ISSUE TITLE
Question mson-react date format

### ISSUE THREAD

**Issue by stove** [redgeoff/mson-react#251]
Hi, tnx for great work. Que: How do I best format value in DateField to show "yyyy-MM-dd" in mson-react?(In DatePicker for example)
Best Regards
Bjorn

**Comment by redgeoff** [comment]
Good question!

Here are two enhancements that I just committed to mson and mson-react that enable this:
- https://github.com/redgeoff/mson/pull/318
- https://github.com/redgeoff/mson-react/pull/252

Now all you need to do is specify a `format`, e.g.
```js
    {
      name: 'dateField',
      component: 'DateField',
      label: 'DateField',
      format: 'yyyy-MM-dd'
    },
```

**Comment by stove** [comment]
Ok! Thanks a bunch!

/Bjorn
