### ISSUE TITLE
Does not compile by using material-ui-pickers v2.x.x

### ISSUE THREAD

**Issue by highfield** [redgeoff/mson-react#71]
I'm not sure if this topic was already covered, but I'm unable to compile my project by using a 2.x.x version of the material-ui-pickers package.

You can try on CodeSand as well, which logs something like:

> Error in sandbox: 
> ModuleNotFoundError: Could not find module in path: 'material-ui-pickers/utils/date-fns-utils' relative to '/node_modules/mson-react/lib/fields/date-field.js'
> Error in sandbox: 
> ModuleNotFoundError: Could not find module in path: 'material-ui-pickers/utils/date-fns-utils' relative to '/node_modules/mson-react/lib/fields/date-field.js'

**Comment by redgeoff** [comment]
Hi @highfield! This should now be fixed by MSON 1.2.0. Thanks!

**Comment by highfield** [comment]
Perfect! Many thanks.
