### ISSUE TITLE
Add @date-io/date-fns, date-fns and material-ui-pickers as dependencies (no alpha)

### ISSUE THREAD

**Issue by ssolidus** [redgeoff/mson-react#88]
Getting the following error after installing `mson-react`. I tried adding `mson` too.
```bash
./node_modules/mson-react/lib/fields/date-field.js
Module not found: Can't resolve '@date-io/date-fns' in 
'/home/user/dexter/client/node_modules/mson-react/lib/fields'
```

and

```bash
./node_modules/mson-react/lib/fields/date-field.js                                                            
Module not found: Can't resolve 'material-ui-pickers/DatePicker' in '/home/user/dexter/client/node_modules/react/lib/fields'        
```

**Comment by redgeoff** [comment]
Those deps are [peerDependencies](https://github.com/redgeoff/mson-react/blob/master/package.json#L9). Check out [mson-getting-started](https://github.com/redgeoff/mson-getting-started/blob/master/package.json) for more info

**Comment by ssolidus** [comment]
@redgeoff please, dedicate some more time to making your packages work out of the box with `yarn add` or `npm install`. I shouldn't have to clone your packages and `yarn link` them.

**Comment by redgeoff** [comment]
Yarn linking is not needed unless you are making chnages to mson and
mson-react. See mson-getting-started for a working example without yarn link

**Comment by ssolidus** [comment]
@redgeoff as I said above, I should not need to go there to find out what dependencies need to be in my `package.json`. I should be able to get everything working right away just by adding the package.

Also, you didn't respond to my other points - I am giving you some suggestions that other node modules mostly all have, because I would like to be able to use MSON at some point.

**Comment by ssolidus** [comment]
@redgeoff https://medium.com/@jacob.h.page/common-npm-mistakes-51bf8989079f

**Comment by lobo** [comment]
@redgeoff such a bummer man, a big PITA
100% agreed with @ssolidus

**Comment by lobo** [comment]
@redgeoff can you please explain somewhere how the hell do I get this running?

**Comment by redgeoff** [comment]
I've just added the following to [Adding MSON-React to Your Existing React Project](https://github.com/redgeoff/mson-react/blob/master/README.md#adding-mson-react-to-your-existing-react-project):

### Adding MSON-React to Your Existing React Project

  - `yarn add @date-io/date-fns @material-ui/core date-fns material-ui-pickers mson mson-react typeface-roboto`
    - Note: this is needed as MSON and MSON-React are libraries that work in conjunction with React, Material UI and Date-IO. As such, these dependencies are peer dependencies.
  - Add the following to the head section of your index.html:
    ```html
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    ```
    Note: MSON-React uses font icons as the user can specify any Icon during runtime and the alternative of bundling all the icons as SVG icons would make your JS bundle **huge**

**Comment by ssolidus** [comment]
@redgeoff you are misunderstanding what a peer dependency is - in this case, `mson-react` would be a peer dependency, and all its dependencies would be regular dependencies of it.

Also, `mson` would be a regular dependency of `mson-react`, not a peer dependency.

Please, read the article I linked above and fix your project.

**Comment by redgeoff** [comment]
I appreciate your persistence here, but I see things differently. Consider an app that is already using material-ui, material-ui-pickers and date-fns, which are all common libraries used by React apps. The developers then want to add mson-react and not duplicate the libraries they are currently using. To prevent this duplication of common libraries, mson-react uses peerDependencies.

**Comment by lobo** [comment]
```
npm WARN mson-react@1.2.0 requires a peer of date-fns@^2.0.0-alpha.21 but none is installed. You must install peer dependencies yourself.
npm WARN @date-io/date-fns@1.1.0 requires a peer of date-fns@2.0.0-alpha.27 but none is installed. You must install peer dependencies yourself.
```

**Comment by lobo** [comment]
What @ssolidus is saying is the same as me, I follow your link https://github.com/redgeoff/mson-react/blob/master/README.md#adding-mson-react-to-your-existing-react-project or tutorial, and I still get this problem. And none of my code works!

**Comment by lobo** [comment]
Hence: 

1. Your tutorial is either useless or incomplete.
2. This is definitely not the best approach for users to make your lib work (people like me who just want to do `npm i --save xxxx`

**Comment by lobo** [comment]
When the system tries to compile it, you get stuff like:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'date-fns/addDays'
```

**Comment by redgeoff** [comment]
@lobo, I appreciate your continued interest in MSON, but I'd highly recommend that you check your tone. Open source projects are volunteer lead and abrasive comments like yours sour the joy that we open-source contributors get from volunteering our time.

That being said, I did have a tiny error in my instructions, i.e. you need `yarn add date-fns@2.0.0-alpha.27` and not `yarn add date-fns`. It is not ideal that the alpha lib is required, but this is a requirement of `@date-io/date-fns`, which is required by `material-ui-pickers`. Soon, this will not be the case and the latest non-alpha packages will just work.

Also, I confirmed the steps are working by:
1. `npx create-react-app my-app`
2. `cd my-app`
3. Following the steps at [Adding MSON-React to Your Existing React Project](https://github.com/redgeoff/mson-react/blob/master/README.md#adding-mson-react-to-your-existing-react-project)
